eastwood/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('employee/', include('employeeBase.urls')),
    path('admin/', admin.site.urls),
]

employeeBase/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name = 'employee'
urlpatterns = [
    re_path(r'^$', views.index, name='index' ),
    path('list/', views.EmployeeList.as_view(), name = 'list'),
    re_path(r'^detail/(?P<pk>[0-9]+)/$', views.EmployeeDetail.as_view(), name = 'detail'),
    path('alfabet/',views.EmployeeAlfabet.as_view(), name = 'alfabet')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employeeBase/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    name = models.CharField('Отдел', max_length = 20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'

class Employee(models.Model):
    name = models.CharField('Имя', max_length = 20)
    surname = models.CharField('Фамилия', max_length = 20)
    patronymic = models.CharField('Отчество', max_length = 20)
    birth_day = models.DateField()
    email = models.EmailField()
    tel = models.CharField('Телефон', max_length = 20)
    begin_work = models.DateField(auto_now_add=True)
    end_work = models.DateField(null = True, blank = True)
    Position =  models.CharField('Должность', max_length = 30)
    departament = models.ForeignKey(Department, on_delete = models.CASCADE, verbose_name = 'Отдел')

    def __str__(self):
        return self.patronymic

    def __str__(self):
        return self.name

    def __str__(self):
        return self.surname

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

employeeBase/views.py
from django.shortcuts import render
import datetime
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from django.db.models.functions import Substr, Upper
from .models import Department, Employee

# Create your views here.
def letters(self):

    letters =list([f['fl'] for f in Employee.objects.annotate(fl=Upper(Substr('surname', 1, 1))).values('fl')])
    k,m = divmod(len(letters),7)
    letgroups = tuple((letters[i * k + min(i, m):(i + 1) * k + min(i + 1, m)]  for i in range(7)))
    str_for_links = { id:min(val) + '-' + max(val) for id, val in  enumerate(letgroups) if val}
    return {
            'letgroups':letgroups,
            'letters':letters,
            'str_for_links': str_for_links
      }

class EmployeeList(ListView):
    model = Employee
    paginate_by = 2
    #
    def get_queryset(self,  **kwargs):
        try:
            by_departament = Employee.objects.filter(departament = self.request.GET['departament'])
            if self.request.GET['is_work'] == 'work':
                return by_departament.filter(end_work = None)
            else:
                return by_departament.exclude(end_work = None)
            return Employee.objects.filter(departament = self.request.GET['departament']).filter()
        except KeyError:
            return Employee.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EmployeeList, self).get_context_data(**kwargs)
        context['departaments'] = Department.objects.all()
        return context

class EmployeeDetail(DetailView):
    model = Employee

class EmployeeAlfabet(ListView):
    model = Employee
    template_name = 'employeeBase/employee_alfabet.html'
    def  get_queryset(self,  **kwargs):
        # группы букв
        letgroups = letters(self)

        try:
            get_letters = self.request.GET['letters']
            return Employee.objects.annotate(fl=Upper(Substr('surname', 1, 1))).filter(fl__in = letgroups['letgroups'][int(self.request.GET['letters'])])
        except KeyError:
            return Employee.objects.annotate(fl=Upper(Substr('surname', 1, 1))).filter(fl__in = letgroups['letgroups'][0])

    def get_context_data(self, **kwargs):
        context = super(EmployeeAlfabet, self).get_context_data(**kwargs)
        letgroups = letters(self)
        context['str_for_links'] =letgroups['str_for_links']
        return context

def index(request):
    q = {}
    return render(request, 'employeeBase/index.html', context = q)

employeeBase/templates/employeeBase/employee_alfabet.html
{% extends "employeeBase/wrapper.html" %} {% block content %} {% load staticfiles %}
<div class="container">

<h1 class="heads">Алфавитный список работников</h1>
<div class=" up_string" >
    {% for link,str in str_for_links.items %}
    <span class="alfabet" >
        <a href="{% url 'employee:alfabet'%}?letters={{link}}">{{str}}</a>
    </span>
    {% endfor %}
</div>
<div class="surname_list">
    {% for employee in object_list%}
        <p><a href="{% url 'employee:detail' employee.id %}">{{employee}}</a></p>
    {% endfor %}
    </div>
</div>
    {%endblock%}

employeeBase/templates/employeeBase/employee_detail.html
{% extends "employeeBase/wrapper.html" %} {% block content %} {% load staticfiles %}
<div class="container">
    <h3>Информация о работнике :</h3>
    <br />{{object.name}}
    <br />{{object.surname}}
    <br />{{object.patronymic}}
    <br />{{object.birth_day}}
    <br />{{object.email}}
    <br />{{object.tel}}
    <br />{{object.begin_work}}
    <br />
    {% if  object.end_work %}
        уволен {{object.end_work}}
    {% else %}
        Всё ещё работает
    {% endif %}
    <br />{{object.Position}}
    <br />Отдел {{object.departament}}
    <br /><a href="{% url 'employee:list' %}">К списку</a>
</div>
{%endblock%}

employeeBase/templates/employeeBase/employee_list.html
{% extends "employeeBase/wrapper.html" %} {% block content %} {% load staticfiles %}
<div class="container">

<h1 class="heads" >Список сотрудников:</h1>

<form action="">
    <select class="" name="departament">
        {% for departament in departaments  %}
            <option value="{{departament.id}}">
                Отдел {{departament}}
                </option>
        {% endfor %}
    </select>
    <select class="" name="is_work">
        <option value="work">Всё ещё работает</option>
        <option value="fired">Уволен</option>
    </select>
    <button name="filters" value="1" type="submit">Применить</button>
    <a href="{% url 'employee:list' %}">Полный список</a>
    </form>

{% for employee in object_list  %}
    <p><a href="{% url 'employee:detail' employee.id %}">{{employee}}</a></p>
{% endfor %}

{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'employee:list' %}?page={{ page_obj.previous_page_number }}">Назад</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'employee:list' %}?page={{ page_obj.next_page_number }}">Вперёд</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    <a href="{% url 'employee:alfabet' %}"> алфавитный список</a>
    </div>
{%endblock%}

employeeBase/templates/employeeBase/index.html
{% extends "employeeBase/wrapper.html" %} {% load staticfiles %}
{% block content %}
<div class="container">
    <a href="{% url 'employee:list' %}" >Работники по фильтрам</a>
    <br /><a href="{% url 'employee:alfabet' %}"> Алфавитный список</a>
    </div>
{% endblock %}

employeeBase/templates/employeeBase/wrapper.html
<!DOCTYPE html>
<html lang="ru">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>employeeBase</title>

{% load staticfiles %}
<!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'employeeBase/css/employee.css' %}"
    type="text/css" >
</head>
{% block content %}
{% endblock %}